### ISSUE TITLE
deprecation error

### ISSUE THREAD

**Issue by contra** [syndbg/webpack-google-cloud-storage-plugin#10]
```
(node:13210) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at WebpackGoogleCloudStoragePlugin.apply (/Users/contra/Projects/staeco/node_modules/webpack-google-cloud-storage-plugin/dist/webpack-google-cloud-storage-plugin.js:218:17)
    at webpack (/Users/contra/Projects/staeco/node_modules/webpack/lib/webpack.js:37:12)
    at Object.<anonymous> (/Users/contra/Projects/staeco/bin/build/cli.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at loader (/Users/contra/Projects/staeco/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/contra/Projects/staeco/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/contra/Projects/staeco/bin/build/index.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:240:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:564:3)
```

just a heads up ^ looks like the latest webpack just started doing this today

**Comment by contra** [comment]
@syndbg Would you take a PR to fix this?

**Comment by syndbg** [comment]
@contra Accepting help. Currently I'm very detach from the webpack community and will need a significant time to catch up on their API changes :/
