### ISSUE TITLE
GCS Resumable Upload Error

### ISSUE THREAD

**Issue by lnlwd** [syndbg/webpack-google-cloud-storage-plugin#4]
I got this error twice while trying to upload file with webpack. Can anyone help?

```
node_modules/gcs-resumable-upload/index.js:326
  this.configStore.del(this.file)

TypeError: this.configStore.del is not a function
    at Upload.deleteConfig (/node_modules/gcs-resumable-upload/index.js:326:20)
    at Request.<anonymous> (/node_modules/gcs-resumable-upload/index.js:172:12)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/node_modules/request/request.js:1171:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by lnlwd** [comment]
Fixed on stephenplusplus/gcs-resumable-upload#18 i'll close this issue 😄

**Comment by syndbg** [comment]
How was this related to the `webpack-google-cloud-storage-plugin`?

**Comment by lnlwd** [comment]
GCS Resumable Upload is one of  the dependencies of @google-cloud/storage
